apiVersion: apps/v1
kind: Deployment
metadata:
  name: ransim
  namespace: ai-cloud-ran-genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ransim
  template:
    metadata:
      labels:
        app: ransim
    spec:
      serviceAccountName: ransim-sa
      containers:
      - name: ransim
        image: quay.io/dlakshma/ransim:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_HOST
          value: '[INSERT_HERE_KAFKA_HOST]'
        command: ["python", "-u", "ransim.py"]
        securityContext:
          privileged: true
          runAsUser: 0
