apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-forecast
  labels:
    app: forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecast
  template:
    metadata:
      labels:
        app: forecast
    spec:
      containers:
      - name: forecast
        image: quay.io/ferossi/agentforecast:0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: agent-forecast-secrets
              key: S3_KEY
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: agent-forecast-secrets
              key: S3_SECRET_ACCESS_KEY
        - name: S3_HOST
          value: '[S3_HOST]'
        - name: S3_BUCKET
          value: '[S3_BUCKET]' 
        ports:
        - containerPort: 5001
