apiVersion: v1
kind: Service
metadata:
  name: agent-forecast-service
  labels:
    app: forecast
spec:
  selector:
    app: forecast
  ports:
    - protocol: TCP
      port: 5001      
      targetPort: 5001
  type: ClusterIP
